<?php

use Illuminate\Database\Seeder;

class BlogsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('blogs')->insert([
            [
                'title' => 'Former Microsoft Engineer Gets Prison for Role in Reveton Ransomware',
                'slug' => 'former-microsoft-engineer-gets-prison-for-role-in-reveton-ransomware',
                'image' => '2018_11_06_defd6378da52610c97fa613fae69e13b.jpg',
                'teaser' => 'A former Microsoft network engineer who was charged in April this year has now been sentenced to 18 months in prison after pleading guil...',
                'content' => '<div dir="ltr">A former Microsoft network engineer who was charged in April this year has now been&nbsp;<a href="https://www.justice.gov/opa/pr/washington-state-man-sentenced-prison-role-connection-reveton-ransomware" target="_blank" rel="nofollow noopener">sentenced</a>&nbsp;to 18 months in prison after pleading guilty to money laundering in connection with the Reveton ransomware.<br /><br />Reveton malware is old ransomware, also known as scareware or police ransomware that instead of encrypting files locks the screen of victims&rsquo; computers and displays a message purporting to come from a national law enforcement agency.<br /><br />The splash screen of the malware was designed to falsely tell unsuspecting victims that they have been caught doing illegal or malicious activities online or the law enforcement had found illegal material on their computer, forcing users to make pay a "fine" of $200-300 within 48 hours to regain access to their computers.<br /><br />Raymond Odigie Uadiale, 41-year-old, who worked as a Microsoft network engineer, is not the actual&nbsp;<a href="https://thehackernews.com/2013/02/group-behind-largest-ransomware.html" target="_blank" rel="noopener">author of the Reveton ransomware</a>, but he helped the Reveton distributor, residing in the UK and identified as the online moniker "K!NG," in cashing out ransom money collected from victims in the form of Green Dot MoneyPak prepaid vouchers.<br />
                    <div class="ad_two clear">&nbsp;</div>
                    <br />Uadiale, who was a student at Florida International University at the time of his crime in 2012 and 2013, was said to have acquired MoneyPak debit cards under the fake name of Mike Roland and received payments from victims of Reveton.<br /><br />Using Liberty Reserve service, Uadiale then transferred $93,640 into accounts of his unnamed co-conspirator in the United Kingdom, after keeping his 30 percent cut.<br />
                    <div class="separator"><a href="https://1.bp.blogspot.com/-5Og_TmLKTI0/W3Pqxt5mbqI/AAAAAAAAx3I/oQxtkinSx_QTz-9ZD4e_mbQHVsi8erDsQCLcBGAs/s728-e100/microsoft-reveton-police-ransomware.png"><img title="microsoft reveton police ransomware" src="https://1.bp.blogspot.com/-5Og_TmLKTI0/W3Pqxt5mbqI/AAAAAAAAx3I/oQxtkinSx_QTz-9ZD4e_mbQHVsi8erDsQCLcBGAs/s728-e100/microsoft-reveton-police-ransomware.png" alt="microsoft reveton police ransomware" border="0" data-original-height="380" data-original-width="728" /></a></div>
                    Liberty Reserve was itself closed down by US authorities in May 2013, after its creator pleaded guilty to laundering hundreds of millions of dollars through the digital currency exchange and was sentenced to 20 years in prison.<br /><br />In the Southern Florida US District Court on Monday, Uadiale was given an 18-month prison sentence and three years of supervised release, after he agreed to a plea agreement that dismissed the second count of substantive money laundering.<br />
                    <blockquote class="tr_bq">"The indictment charged Uadiale with one count of conspiracy to commit money laundering and one count of substantive money laundering. As part of the plea agreement, the government dismissed the substantive count."</blockquote>
                    <blockquote class="tr_bq">"By cashing out and then laundering victim payments, Raymond Uadiale played an essential role in an international criminal operation that victimized unsuspecting Americans by infecting their computers with malicious ransomware," said Assistant Attorney General Brian Benczkowski.</blockquote>
                    Microsoft hired Uadiale as a network engineer after the conspiracy charged related to the ransomware scheme in the indictment ended.</div>
                    <p>&nbsp;</p>
                    <div class="cf note-b">Have something to say about this article? Comment below or share it with us on&nbsp;<a href="https://www.facebook.com/thehackernews" target="_blank" rel="nofollow noopener">Facebook</a>,&nbsp;<a href="https://twitter.com/thehackersnews" target="_blank" rel="nofollow noopener">Twitter</a>&nbsp;or our&nbsp;<a href="https://www.linkedin.com/company/the-hacker-news/" target="_blank" rel="nofollow noopener">LinkedIn Group</a>.</div>',
                'active' => 1,
                'hot' => 1,
                'category_id' =>4
            ],
            [
                'title' => 'Foreshadow Attacks — 3 New Intel CPU Side-Channel Flaws Discovered',
                'slug' => 'foreshadow-attacks-—-3-new-intel-cpu-side-channel-flaws-discovered',
                'image' => '2018_11_06_d9cac0bfef82e451593130300213ebc5.png',
                'teaser' => '2018 has been quite a tough year for Intel. While the chip-maker giant is still dealing with Meltdown and Spectre processor vulnerabil...',
                'content' => '<div dir="ltr">2018 has been quite a tough year for Intel.<br /><br />While the chip-maker giant is still dealing with&nbsp;<a href="https://thehackernews.com/2018/02/meltdown-spectre-malware-hacking.html" target="_blank" rel="noopener">Meltdown and Spectre</a>&nbsp;processor vulnerabilities, yet another major&nbsp;<a href="https://thehackernews.com/2018/01/intel-amt-vulnerability.html" target="_blank" rel="noopener">speculative execution flaw</a>&nbsp;has been revealed in Intels Core and Xeon lines of processors that may leave users vulnerable to cyber-attacks.<br /><br />Dubbed&nbsp;<strong>Foreshadow</strong>, alternatively called L1 Terminal Fault or L1TF, the new attacks include three new speculative execution side-channel vulnerabilities affecting Intel processors.<br />
                    <div class="ad_two clear">&nbsp;</div>
                    <br />The Foreshadow attacks could allow a hacker or malicious application to gain access to the sensitive data stored in a computers memory or third-party clouds, including files, encryption keys, pictures, or passwords.<br /><br />The three Foreshadow vulnerabilities have been categorized into two variants:<br /><br />
                    <h2>1.) Foreshadow</h2>
                    <br />Foreshadow (<a href="https://foreshadowattack.eu/foreshadow.pdf" target="_blank" rel="nofollow noopener">PDF</a>) targets a new technology originally been designed to protect select code and users data from disclosure or modification, even if the entire system falls under attack:<br /><br />
                    <ul>
                    <li><strong>Intel Software Guard Extensions (SGX) &mdash; CVE-2018-3615</strong></li>
                    </ul>
                    <br />The new attack against SGX enclaves, which is resilient to&nbsp;<a href="https://thehackernews.com/2018/01/meltdown-spectre-patches.html" target="_blank" rel="noopener">Meltdown and Spectre attacks</a>, may allow an unauthorized attacker to steal information residing in the L1 data cache&mdash;a protected portion of a chips core memory that holds things like passwords and encryption keys&mdash;via side-channel analysis.<br /><br />
                    <blockquote class="tr_bq">"Foreshadow enables an attacker to extract SGX sealing keys, previously sealed data can be modified and re-sealed," the researchers&nbsp;<a href="https://foreshadowattack.eu/" target="_blank" rel="nofollow noopener">said</a>. "With the extracted sealing key, an attacker can trivially calculate a valid Message Authentication Code (MAC), thus depriving the data owner from the ability to detect the modification."</blockquote>
                    <br />
                    <h2>2.) Foreshadow: Next Generation (NG)</h2>
                    <div class="video-container"><iframe src="https://www.youtube.com/embed/8ZF6kX6z7pM?rel=0" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen" data-mce-fragment="1"></iframe></div>
                    The second variant (<a href="https://foreshadowattack.eu/foreshadow-NG.pdf" target="_blank" rel="nofollow noopener">PDF</a>) includes two vulnerabilities, which target virtualization environments being used by large cloud computing providers like Amazon and Microsoft:<br /><br />
                    <ul>
                    <li><strong>Operating systems and System Management Mode (SMM) &mdash; CVE-2018-3620</strong></li>
                    <li><strong>Virtualization software and Virtual Machine Monitors (VMM) &mdash; CVE-2018-3646</strong></li>
                    </ul>
                    <br />These flaws also disclose sensitive information residing in the L1 data cache, including the information stored in other virtual machines running on the same third-party cloud, with local user access or guest OS privilege via a terminal page fault and side-channel analysis.<br /><br />
                    <blockquote class="tr_bq">"Using Foreshadow-NG, a malicious program running on the computer might be able to read some parts of the kernels data," the researchers said. "As the kernel has access to data stored by other programs, a malicious program might be able to exploit Foreshadow-NG to access data belonging to other programs."</blockquote>
                    <br />
                    <h2>Intel and Partners Releases Patches for Foreshadow Flaws</h2>
                    <br />Since the mitigations available for&nbsp;<a href="https://thehackernews.com/2018/01/meltdown-spectre-vulnerability.html" target="_blank" rel="noopener">Meltdown and Spectre</a>&nbsp;are not sufficient to patch above mentioned-Foreshadow vulnerabilities, Intel and partners need to roll out new security patches at both software and microcode level.<br /><br />
                    <blockquote class="tr_bq">"Foreshadow is different from Meltdown as it targets virtual machines and SGX in addition to data stored in the operating systems kernel (which was targeted by Meltdown)," the researchers said.</blockquote>
                    <br />You can see video demonstrations illustrating the Foreshadow vulnerabilities as well.<br />
                    <div class="video-container"><iframe src="https://www.youtube.com/embed/n_pa2AisRUs?rel=0" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen" data-mce-fragment="1"></iframe></div>
                    <br />
                    <div class="video-container"><iframe src="https://www.youtube.com/embed/ynB1inl4G3c?rel=0" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen" data-mce-fragment="1"></iframe></div>
                    <br />Since SGX is only supported in Intel processors, the Foreshadow bugs only affect Intel processors, though researchers have yet to test Foreshadow against ARM and AMD processors.<br />
                    <div class="ad_two clear">&nbsp;</div>
                    <br />According to Intel, none of these attacks so far appear to have been seen in the wild, and the company has started releasing patches for all the new speculative execution flaws. You can check the status of the security patches&nbsp;<a href="https://www.intel.com/content/dam/www/public/us/en/documents/sa00115-microcode-update-guidance.pdf" target="_blank" rel="nofollow noopener">here</a>.<br /><br />Besides Intel,&nbsp;<a href="https://blogs.technet.microsoft.com/srd/2018/08/10/analysis-and-mitigation-of-l1-terminal-fault-l1tf/" target="_blank" rel="nofollow noopener">Microsoft</a>&nbsp;and&nbsp;<a href="https://blogs.oracle.com/oraclesecurity/intel-l1tf" target="_blank" rel="nofollow noopener">Oracle</a>&nbsp;on Tuesday also released security advisories and updates for L1TF. Cloud services like&nbsp;<a href="https://docs.microsoft.com/en-us/azure/virtual-machines/windows/mitigate-se" target="_blank" rel="nofollow noopener">Microsoft Azure</a>,&nbsp;<a href="https://aws.amazon.com/security/security-bulletins/AWS-2018-019/" target="_blank" rel="nofollow noopener">Amazon Web Services</a>, and&nbsp;<a href="https://cloud.google.com/blog/products/gcp/protecting-against-the-new-l1tf-speculative-vulnerabilities" target="_blank" rel="nofollow noopener">Google Compute Engine</a>have already mitigated the issue.<br /><br />Foreshadow bug was discovered by two teams of researchers&mdash;researchers from imec-DistriNet and KU Leuven; and researchers from Technion, University of Michigan, the University of Adelaide and CSIROs Data61.</div>
                    <p>&nbsp;</p>
                    <div class="cf note-b">Have something to say about this article? Comment below or share it with us on&nbsp;<a href="https://www.facebook.com/thehackernews" target="_blank" rel="nofollow noopener">Facebook</a>,&nbsp;<a href="https://twitter.com/thehackersnews" target="_blank" rel="nofollow noopener">Twitter</a>&nbsp;or our&nbsp;<a href="https://www.linkedin.com/company/the-hacker-news/" target="_blank" rel="nofollow noopener">LinkedIn Group</a>.</div>',
                    'active' => 1,
                    'hot' => 1,
                    'category_id' =>1
            ],
            [
                'title' => 'VINHOMES PHẠM HÙNG SKYLAKE',
                'slug' => 'vinhomes-pham-hung-skyla',
                'image' => '2018_11_05_c4d7f23d107879e7e5cb311e1bda69da.jpg',
                'teaser' => 'Phát triển cuộc sống và sự nghiệp của bạn ngay tại không gian sống của tổ ấm, cùng với những người hàng xóm đồng điệu , ưu tú , hay đơn giản là nhâm nhi một tách café sáng cuối tuần sau những giờ tập sôi động tại phòng gym.',
                'content' => '<p>Khi căn hộ kh&ocirc;ng chỉ l&agrave; căn hộ</p>
                    <p>Khi tổ ấm kh&ocirc;ng chỉ l&agrave; những bước tường nh&agrave;m ch&aacute;n</p>
                    <p>L&agrave; nơi để thưởng thức buổi tối giữa c&aacute;c v&igrave; sao, l&agrave; nơi để thư gi&atilde;n trong bồn tắm v&agrave; ngắm ch&igrave;m cả th&agrave;nh phố s&ocirc;i động về đ&ecirc;m sau mỗi ng&agrave;y d&agrave;i bận rộn</p>
                    <p>Ngự trị đỉnh cao kh&ocirc;ng đơn thuần l&agrave; sỡ hữu vị tr&iacute; cao nhất của t&ograve;a nh&agrave;, đ&oacute; c&ograve;n l&agrave; những x&uacute;c cảm độc t&ocirc;n chỉ ri&ecirc;ng d&agrave;nh cho những chủ nh&acirc;n đẳng cấp.</p>
                    <p>H&atilde;y để SẮC XANH DƯƠNG&nbsp; v&agrave; kh&ocirc;ng gian sống trong l&agrave;nh, tiện nghi của Vinhomes Skylake ch&agrave;o đ&oacute;n bạn trở về mỗi ng&agrave;y.</p>
                    <p><strong>Vinhomes Phạm Hưng &ndash; Vinhomes Sky Lake&nbsp;</strong>l&agrave; dự &aacute;n tổ hợp TTTM v&agrave; 1812 căn hộ được x&acirc;y dựng theo ti&ecirc;u chuẩn 5 sao tại trung t&acirc;m th&agrave;nh phố h&agrave; nội .</p>
                    <ul>
                    <li><strong>T&ecirc;n dự &aacute;n</strong>: VINHOMES PHẠM H&Ugrave;NG</li>
                    <li><strong>Chủ đầu tư dự &aacute;n</strong>: C&ocirc;ng ty TNHH Ph&aacute;t Triển C&ocirc;ng Vi&ecirc;n Trung T&acirc;m</li>
                    <li><strong>Vị tr&iacute; dự &aacute;n</strong>: mặt đường Phạm H&ugrave;ng &ndash; Quận Từ Li&ecirc;m &ndash; Thanh Phố H&agrave; Nội</li>
                    <li><strong>Tổng diện t&iacute;ch dự &aacute;n</strong>: 23.134,3 m2</li>
                    <li><strong>Tổng diện t&iacute;ch s&agrave;n x&acirc;y dựng</strong>: 32.000 m2</li>
                    <li><strong>Mật độ x&acirc;y dựng</strong>: 49,94% ( khối đế).26,49% (khối th&aacute;p)</li>
                    <li><strong>Loại h&igrave;nh ph&aacute;t triển</strong>: Tổ hợp TTTM, dịch vụ</li>
                    <li><strong>Quy m&ocirc; dự &aacute;n</strong>: Gồm 3 t&ograve;a chung cư cao từ 37 &ndash; 42 tầng, S1 S2 chung khối đế, S3 c&oacute; khối đế ri&ecirc;ng, 3 tầng hầm, 3 tầng TTTM c&oacute; Penhouse v&agrave; Shophouse khối đế.</li>
                    <li><strong>Số lượng căn hộ</strong>: 1826 căn</li>
                    <li><strong>Cơ cấu căn hộ</strong>: C&aacute;c căn hộ được thiết kế từ 41,52-176m2 với 1-4 ph&ograve;ng ngủ</li>
                    <li><strong>Khởi c&ocirc;ng</strong>:&nbsp;15/11/2016</li>
                    <li><strong>B&agrave;n giao</strong>: Qu&yacute; 2/2019</li>
                    </ul>
                    <p><img class="aligncenter size-full wp-image-207" src="http://sanvinhomes.net/wp-content/uploads/2016/11/96177.jpg" sizes="(max-width: 1280px) 100vw, 1280px" srcset="http://sanvinhomes.net/wp-content/uploads/2016/11/96177.jpg 1280w, http://sanvinhomes.net/wp-content/uploads/2016/11/96177-300x169.jpg 300w, http://sanvinhomes.net/wp-content/uploads/2016/11/96177-768x432.jpg 768w, http://sanvinhomes.net/wp-content/uploads/2016/11/96177-1024x576.jpg 1024w" alt="96177" width="1280" height="720" /></p>
                    <p>Vinhomes Phạm H&ugrave;ng (Vinhomes Sky Lake) l&agrave; tổ hợp dự &aacute;n chung cư, shophouse, văn ph&ograve;ng kết hợp với c&aacute;c dịch vụ thương mại nằm gần tại ng&atilde; ba đường Phạm H&ugrave;ng &ndash; Dương Đ&igrave;nh Nghệ v&agrave; gi&aacute;p với c&ocirc;ng vi&ecirc;n Cầu Giấy mới rộng 32ha. Vinhomes Phạm H&ugrave;ng được chủ đầu tư VinGroup đầu tư x&acirc;y dựng tr&ecirc;n khu đất rộng khoảng 2.3ha với c&aacute;c t&ograve;a chung cư cao khoảng từ 36 &ndash; 41 tầng v&agrave; trang bị đầy đủ c&aacute;c tiện &iacute;ch h&agrave;ng đầu nhằm phục vụ cư d&acirc;n tương lai.</p>
                    <p><strong>NHẤT CẬN THỊ &ndash; NHỊ C&Acirc;N GIANG &ndash; TAM CẬN LỘ</strong></p>
                    <p><strong>VINHOMES PHẠM H&Ugrave;NG</strong>&nbsp;Vinhomes Phạm H&ugrave;ng nằm gần ở ng&atilde; ba đường Phạm H&ugrave;ng v&agrave; Dương Đ&igrave;nh Nghệ, quận Cầu Giấy, H&agrave; Nội. Đ&acirc;y l&agrave; một trong những vị tr&iacute; &ldquo;v&agrave;ng&rdquo; của thủ đ&ocirc; H&agrave; Nội về cơ sở hạ tầng, kết nối giao <p>Khi tổ ấm kh&ocirc;ng chỉ l&agrave; những bước tường nh&agrave;m ch&aacute;n</p>
                    <p>L&agrave; nơi để thưởng thức buổi tối giữa c&aacute;c v&igrave; sao, l&agrave; nơi để thư gi&atilde;n trong bồn tắm v&agrave; ngắm ch&igrave;m cả th&agrave;nh phố s&ocirc;i động về đ&ecirc;m sau mỗi ng&agrave;y d&agrave;i bận rộn</p>
                    <p>Ngự trị đỉnh cao kh&ocirc;ng đơn thuần l&agrave; sỡ hữu vị tr&iacute; cao nhất của t&ograve;a nh&agrave;, đ&oacute; c&ograve;n l&agrave; những x&uacute;c cảm độc t&ocirc;n chỉ ri&ecirc;ng d&agrave;nh cho những chủ nh&acirc;n đẳng cấp.</p>
                    <p>H&atilde;y để SẮC XANH DƯƠNG&nbsp; v&agrave; kh&ocirc;ng gian sống trong l&agrave;nh, tiện nghi của Vinhomes Skylake ch&agrave;o đ&oacute;n bạn trở về mỗi ng&agrave;y.</p>
                    <p><strong>Vinhomes Phạm Hưng &ndash; Vinhomes Sky Lake&nbsp;</strong>l&agrave; dự &aacute;n tổ hợp TTTM v&agrave; 1812 căn hộ được x&acirc;y dựng theo ti&ecirc;u chuẩn 5 sao tại trung t&acirc;m th&agrave;nh phố h&agrave; nội .</p>
                    <ul>
                    <li><strong>T&ecirc;n dự &aacute;n</strong>: VINHOMES PHẠM H&Ugrave;NG</li>
                    <li><strong>Chủ đầu tư dự &aacute;n</strong>: C&ocirc;ng ty TNHH Ph&aacute;t Triển C&ocirc;ng Vi&ecirc;n Trung T&acirc;m</li>
                    <li><strong>Vị tr&iacute; dự &aacute;n</strong>: mặt đường Phạm H&ugrave;ng &ndash; Quận Từ Li&ecirc;m &ndash; Thanh Phố H&agrave; Nội</li>
                    <li><strong>Tổng diện t&iacute;ch dự &aacute;n</strong>: 23.134,3 m2</li>
                    <li><strong>Tổng diện t&iacute;ch s&agrave;n x&acirc;y dựng</strong>: 32.000 m2</li>
                    <li><strong>Mật độ x&acirc;y dựng</strong>: 49,94% ( khối đế).26,49% (khối th&aacute;p)</li>
                    <li><strong>Loại h&igrave;nh ph&aacute;t triển</strong>: Tổ hợp TTTM, dịch vụ</li>
                    <li><strong>Quy m&ocirc; dự &aacute;n</strong>: Gồm 3 t&ograve;a chung cư cao từ 37 &ndash; 42 tầng, S1 S2 chung khối đế, S3 c&oacute; khối đế ri&ecirc;ng, 3 tầng hầm, 3 tầng TTTM c&oacute; Penhouse v&agrave; Shophouse khối đế.</li>
                    <li><strong>Số lượng căn hộ</strong>: 1826 căn</li>
                    <li><strong>Cơ cấu căn hộ</strong>: C&aacute;c căn hộ được thiết kế từ 41,52-176m2 với 1-4 ph&ograve;ng ngủ</li>
                    <li><strong>Khởi c&ocirc;ng</strong>:&nbsp;15/11/2016</li>
                    <li><strong>B&agrave;n giao</strong>: Qu&yacute; 2/2019</li>
                    </ul>
                    <p><img class="aligncenter size-full wp-image-207" src="http://sanvinhomes.net/wp-content/uploads/2016/11/96177.jpg" sizes="(max-width: 1280px) 100vw, 1280px" srcset="http://sanvinhomes.net/wp-content/uploads/2016/11/96177.jpg 1280w, http://sanvinhomes.net/wp-content/uploads/2016/11/96177-300x169.jpg 300w, http://sanvinhomes.net/wp-content/uploads/2016/11/96177-768x432.jpg 768w, http://sanvinhomes.net/wp-content/uploads/2016/11/96177-1024x576.jpg 1024w" alt="96177" width="1280" height="720" /></p>
                    <p>Vinhomes Phạm H&ugrave;ng (Vinhomes Sky Lake) l&agrave; tổ hợp dự &aacute;n chung cư, shophouse, văn ph&ograve;ng kết hợp với c&aacute;c dịch vụ thương mại nằm gần tại ng&atilde; ba đường Phạm H&ugrave;ng &ndash; Dương Đ&igrave;nh Nghệ v&agrave; gi&aacute;p với c&ocirc;ng vi&ecirc;n Cầu Giấy mới rộng 32ha. Vinhomes Phạm H&ugrave;ng được chủ đầu tư VinGroup đầu tư x&acirc;y dựng tr&ecirc;n khu đất rộng khoảng 2.3ha với c&aacute;c t&ograve;a chung cư cao khoảng từ 36 &ndash; 41 tầng v&agrave; trang bị đầy đủ c&aacute;c tiện &iacute;ch h&agrave;ng đầu nhằm phục vụ cư d&acirc;n tương lai.</p>
                    <p><strong>NHẤT CẬN THỊ &ndash; NHỊ C&Acirc;N GIANG &ndash; TAM CẬN LỘ</strong></p>
                    <p><strong>VINHOMES PHẠM H&Ugrave;NG</strong>&nbsp;Vinhomes Phạm H&ugrave;ng nằm gần ở ng&atilde; ba đường Phạm H&ugrave;ng v&agrave; Dương Đ&igrave;nh Nghệ, quận Cầu Giấy, H&agrave; Nội. Đ&acirc;y l&agrave; một trong những vị tr&iacute; &ldquo;v&agrave;ng&rdquo; của thủ đ&ocirc; H&agrave; Nội về cơ sở hạ tầng, kết nối giao th&ocirc;ng cũng như c&aacute;c tiện &iacute;ch cộng đồng.</p>
                    <p><img class="aligncenter size-full wp-image-176" src="http://sanvinhomes.net/wp-content/uploads/2016/11/20161107113006-3560.jpg" sizes="(max-width: 745px) 100vw, 745px" srcset="http://sanvinhomes.net/wp-content/uploads/2016/11/20161107113006-3560.jpg 745w, http://sanvinhomes.net/wp-content/uploads/2016/11/20161107113006-3560-300x180.jpg 300w" alt="20161107113006-3560" width="745" height="447" /></p>
                    <p>&nbsp;</p>
                    <p><strong>Giới hạn dự &aacute;n Vinhomes Phạm H&ugrave;ng:</strong></p>
                    <p>+ Ph&iacute;a Bắc: Gi&aacute;p với c&ocirc;ng vi&ecirc;n Cầu Giấy;</p>
                    <p>+ Ph&iacute;a Nam: Nằm gần với đường Dương Đ&igrave;nh Nghệ;</p>
                    <p>+ Ph&iacute;a Đ&ocirc;ng: Gi&aacute;p với t&ograve;a Mitec;</p>
                    <p>+ Ph&iacute;a T&acirc;y: Gi&aacute;p với đường Phạm H&ugrave;ng;.</p>
                    <p>+Với vị tr&iacute; &ldquo;v&agrave;ng&rdquo; nằm tại mặt đường lớn, cư d&acirc;n Vinhomes phạm h&ugrave;ng c&oacute; thể dễ d&agrave;ng di chuyển ra c&aacute;c trục đường lớn như: Phạm Văn Đồng, Cầu Giấy, Đường 32, Đại lộ Thăng Long, Trần Duy Hưng, Trung K&iacute;nh, Duy T&acirc;n, Mễ Tr&igrave;, L&ecirc; Quang Đạo, &hellip; đường cao tốc tr&ecirc;n kh&ocirc;ng, v&agrave;nh đai 3, v&agrave;nh đai 2, v&agrave;nh đai 2.5, &hellip; Vinhomes Phạm H&ugrave;ng gần rất nhiều dự &aacute;n lớn xung quanh như l&agrave;: Keangnam, Sudico, Five Star Mỹ Đ&igrave;nh, Golden Palace, Golden Palace A, Mbland Trung K&iacute;nh, Chelsea Park, Mandarin Garden, Vinhomes Mễ Tr&igrave;, Vinhomes Trần Duy Hưng, Indochina Plaza, FLC Mỹ Đ&igrave;nh, Dophin Plaza &hellip; Gần nhiều tiện &iacute;ch xung quanh như: C&ocirc;ng vi&ecirc;n cầu giấy, BigC, rạp chiếu phim, cung tri thức H&agrave; Nội, Trung t&acirc;m hội nghị Quốc Gia, S&acirc;n vận động Quốc Gia, khu đ&ocirc; thị Trung H&ograve;a Nh&acirc;n Ch&iacute;nh, bến xe Mỹ Đ&igrave;nh &hellip;</p>
                    <p>Với ưu điểm vượt trội của hạ tầng ti&ecirc;n tiến c&ugrave;ng hệ thống đường bộ v&agrave; đường tr&ecirc;n cao hiện đại tại trung t&acirc;m Mỹ Đ&igrave;nh, Vinhomes Skylake kh&ocirc;ng chỉ l&agrave; chốn an cư,lạc nghiệp được c&aacute;c chủ nh&acirc;n ưu t&uacute; v&agrave; chuy&ecirc;n gia nước ngo&agrave;i &ldquo; chọn mặt gửi v&agrave;ng&rdquo;, m&agrave; c&ograve;n sở hữu những tiềm năng đầu tư kh&ocirc;ng&nbsp; thể chối từ.</p>
                    <p><strong>KIẾN TR&Uacute;C TINH TẾ, TẦM NH&Igrave;N TUYỆT MỸ</strong></p>
                    <p>Kh&ocirc;ng chỉ l&agrave; tuyệt t&aacute;c kiến tr&uacute;c hiện đại, Vinhomes Skylake l&agrave; sự bứt ph&aacute; về kh&ocirc;ng gian, được ấp &ocirc;m bởi thi&ecirc;n nhi&ecirc;n kho&aacute;ng đạt thấm đẫm sắc xanh mộc &ndash; thủy h&ograve;a quyện.</p>
                    <p>Được thiết kế theo phong c&aacute;ch nghỉ dưỡng hiện đại, do AEDAS &ndash; c&ocirc;ng ty tư vấn kiến tr&uacute;c h&agrave;ng đầu thế giới đảm nhận, c&aacute;c căn hộ hướng thủy tại Vinhomes Skylake sỡ hữu ban c&ocirc;ng rộng r&atilde;i l&ecirc;n tới gần 7m2, xứng đ&aacute;ng l&agrave; kh&ocirc;ng gian thư gi&atilde;n l&yacute; tưởng của bạn mỗi ng&agrave;y.</p>
                    <p>Thiết lập &ldquo;c&ocirc;ng vi&ecirc;n bầu trời&rdquo; ngự trị tr&ecirc;n tầng cao, bể bơi tr&agrave;n bờ với thiết kế độc đ&aacute;o c&ugrave;ng những mặt k&iacute;nh d&agrave;i tới 3m ấn tượng, Vinhomes Skylake mang thiết kế chuẩn mực của những &ldquo;dinh thự&rdquo; ven hồ l&yacute; tưởng.</p>
                    <p>Mỗi sản phẩm bất động sản Vinhomes mang theo hơi thở của cuộc sống mới, năng động v&agrave; hiện đại, đồng thời kiến tạo phong c&aacute;ch sống mới cho người d&acirc;n với quy hoạch đồng bộ, nh&agrave; ở chất lượng, dịch vụ xứng tầm, c&ugrave;ng hệ thống tiện &iacute;ch &ldquo;tất cả trong một&rdquo; (All-in-one), m&ocirc;i trường trong l&agrave;nh v&agrave; an ninh đảm bảo. Tất cả tạo n&ecirc;n một hệ gi&aacute; trị sống vượt bậc theo &ldquo;ti&ecirc;u chuẩn Vinhome&rdquo;.</p>
                    <p><img class="aligncenter size-full wp-image-316" src="http://sanvinhomes.net/wp-content/uploads/2016/12/sk1-1.jpg" sizes="(max-width: 1280px) 100vw, 1280px" srcset="http://sanvinhomes.net/wp-content/uploads/2016/12/sk1-1.jpg 1280w, http://sanvinhomes.net/wp-content/uploads/2016/12/sk1-1-300x214.jpg 300w, http://sanvinhomes.net/wp-content/uploads/2016/12/sk1-1-768x548.jpg 768w, http://sanvinhomes.net/wp-content/uploads/2016/12/sk1-1-1024x731.jpg 1024w" alt="sk1" width="1280" height="914" /></p>
                    <ul>
                    <li>&nbsp;Mỗi căn hộ đều sở hữu thiết kế vượt trội với mặt bằng tho&aacute;ng rộng v&agrave; được bố tr&iacute; linh hoạt, gi&uacute;p tối đa c&ocirc;ng năng sử dụng</li>
                    <li>T&ograve;a S1 , S2 được thiết kế&nbsp;bể bơi ngo&agrave;i trời l&agrave;m th&aacute;c tr&agrave;n c&oacute; k&iacute;nh gi&uacute;p qu&yacute; kh&aacute;ch c&oacute; thể nh&igrave;n ra hồ điều h&ograve;a 19ha</li>
                    <li>T&ograve;a S3 được thiết kế bể bơi 4 m&ugrave;a nằm trong t&ograve;a nh&agrave;.</li>
                    <li>T&ograve;a S1 được thiết kế 36 tầng v&agrave; x&acirc;y dựng cảnh quan vườn dưỡng sinh tr&ecirc;n n&oacute;c để lấy view cho S2 v&agrave; S3.</li>
                    <li>100% ph&ograve;ng ngủ đều c&oacute; mặt tho&aacute;ng đ&oacute;n &aacute;nh s&aacute;ng v&agrave; hầu hết c&aacute;c căn đều c&oacute; khe tho&aacute;ng ở khu vực bếp gi&uacute;p cuộc sống nơi đầy c&agrave;ng trở n&ecirc;n gần gũi với thi&ecirc;n nhi&ecirc;n hơn bao giờ hết</li>
                    <li>Nội thất tất cả căn hộ sẽ sử dụng nội thất Koller của Đức</li>
                    <li>Tất cả c&aacute;c mặt ngo&agrave;i sẽ được bao bọc phần lớn bằng k&iacute;nh low-e để tận dụng tối đa view hồ<br /><img class="aligncenter size-full wp-image-374" src="http://sanvinhomes.net/wp-content/uploads/2016/11/16711561_171246140038083_3382356589880528273_n.jpg" sizes="(max-width: 960px) 100vw, 960px" srcset="http://sanvinhomes.net/wp-content/uploads/2016/11/16711561_171246140038083_3382356589880528273_n.jpg 960w, http://sanvinhomes.net/wp-content/uploads/2016/11/16711561_171246140038083_3382356589880528273_n-300x208.jpg 300w, http://sanvinhomes.net/wp-content/uploads/2016/11/16711561_171246140038083_3382356589880528273_n-768x534.jpg 768w" alt="16711561_171246140038083_3382356589880528273_n" width="960" height="667" /></li>
                    </ul>
                    <p>&nbsp;</p>
                    <p><strong>MẶT BẰNG T&Ograve;A S3</strong></p>
                    <p><strong>T&ograve;a S3</strong></p>
                    <p>Số tầng: 42 tầng.<br />Mật độ:20 căn/s&agrave;n.<br />Số thang m&aacute;y:&nbsp;13<br />Diện t&iacute;ch (T4 &ndash; T24): 50,99m2-170m2.<br />&ndash; 2&nbsp;căn 1PN/s&agrave;n: 50,99m2.&nbsp;<strong>Gi&aacute; chỉ &nbsp;từ 1,9 tỷ &nbsp;( Full Vat + Nội thất )&nbsp;</strong><strong>&nbsp;</strong><br />&ndash; 8 căn 2PN/s&agrave;n: 62m2 &ndash; 74,4m2.&nbsp;<strong>Gi&aacute; chỉ từ 2,6 tỷ&nbsp;( Full Vat + Nội thất )&nbsp;</strong><br />&ndash; 8 căn 3PN/s&agrave;n: 90m2 &ndash; 118m2.&nbsp;<strong>Gi&aacute; chỉ từ 4,1 tỷ&nbsp;( Full Vat + Nội thất )</strong><br />&ndash; 2 căn 4PN/s&agrave;n:170m2 &nbsp;<strong>Gi&aacute; chỉ từ 9 tỷ&nbsp;( Full Vat + Nội thất )</strong></p>
                    <p>Tầng 23: Sử dụng l&agrave;m ph&ograve;ng kỹ thuật.</p>
                    <p><strong>DỊCH VỤ 5 SAO CỘNG ĐỒNG ĐẲNG CẤP</strong></p>
                    <p>Ph&aacute;t triển cuộc sống v&agrave; sự nghiệp của bạn ngay tại kh&ocirc;ng gian sống của tổ ấm, c&ugrave;ng với những người h&agrave;ng x&oacute;m đồng điệu , ưu t&uacute; , hay đơn giản l&agrave; nh&acirc;m nhi một t&aacute;ch caf&eacute; s&aacute;ng cuối tuần sau những giờ tập s&ocirc;i động tại ph&ograve;ng gym.</p>
                    <p>Dịch vụ quản l&yacute; theo ti&ecirc;u chuẩn 5 sao của Vinhomes sẽ l&agrave; &ldquo;trợ thủ đắc lực&rdquo;, gi&uacute;p bạn tận hưởng trọn vẹn quỹ thời gian qu&yacute; gi&aacute; của m&igrave;nh cho gia đ&igrave;nh v&agrave; sự nghiệp.</p>
                    <p>Năm trong khu vực được nhiều người nước ngo&agrave;i lựa chọn bởi ti&ecirc;u chuẩn quốc tế cao, c&ugrave;ng khung gian sống như mơ với mật độ c&acirc;y xanh v&agrave; diện t&iacute;ch mặt nước l&yacute; tưởng, Vinhomes Skylake sẽ l&agrave; &ldquo;mảng đ&aacute;t v&agrave;ng&rdquo; quy tụ cộng đồng cư d&acirc;n đẳng cấp.</p>
                    <p>Kh&ocirc;ng chỉ thoải m&atilde;n những y&ecirc;u cầu khắt khe về tiện &iacute;ch sống, Vinhomes Skylake c&ograve;n l&agrave; nơi cuộc sống th&ecirc;m thăng hoa khi những t&acirc;m hồn đồng điệu t&igrave;m thấy nhau, khi gi&aacute; trị văn h&oacute;a v&agrave; nh&acirc;n văn được tr&acirc;n trọng</p>
                    <p><img class="aligncenter size-full wp-image-217" src="http://sanvinhomes.net/wp-content/uploads/2016/11/99707.jpg" sizes="(max-width: 960px) 100vw, 960px" srcset="http://sanvinhomes.net/wp-content/uploads/2016/11/99707.jpg 960w, http://sanvinhomes.net/wp-content/uploads/2016/11/99707-300x167.jpg 300w, http://sanvinhomes.net/wp-content/uploads/2016/11/99707-768x426.jpg 768w" alt="99707" width="960" height="533" /></p>,th&ocirc;ng cũng như c&aacute;c tiện &iacute;ch cộng đồng.</p>
                    <p><img class="aligncenter size-full wp-image-176" src="http://sanvinhomes.net/wp-content/uploads/2016/11/20161107113006-3560.jpg" sizes="(max-width: 745px) 100vw, 745px" srcset="http://sanvinhomes.net/wp-content/uploads/2016/11/20161107113006-3560.jpg 745w, http://sanvinhomes.net/wp-content/uploads/2016/11/20161107113006-3560-300x180.jpg 300w" alt="20161107113006-3560" width="745" height="447" /></p>
                    <p>&nbsp;</p>
                    <p><strong>Giới hạn dự &aacute;n Vinhomes Phạm H&ugrave;ng:</strong></p>
                    <p>+ Ph&iacute;a Bắc: Gi&aacute;p với c&ocirc;ng vi&ecirc;n Cầu Giấy;</p>
                    <p>+ Ph&iacute;a Nam: Nằm gần với đường Dương Đ&igrave;nh Nghệ;</p>
                    <p>+ Ph&iacute;a Đ&ocirc;ng: Gi&aacute;p với t&ograve;a Mitec;</p>
                    <p>+ Ph&iacute;a T&acirc;y: Gi&aacute;p với đường Phạm H&ugrave;ng;.</p>
                    <p>+Với vị tr&iacute; &ldquo;v&agrave;ng&rdquo; nằm tại mặt đường lớn, cư d&acirc;n Vinhomes phạm h&ugrave;ng c&oacute; thể dễ d&agrave;ng di chuyển ra c&aacute;c trục đường lớn như: Phạm Văn Đồng, Cầu Giấy, Đường 32, Đại lộ Thăng Long, Trần Duy Hưng, Trung K&iacute;nh, Duy T&acirc;n, Mễ Tr&igrave;, L&ecirc; Quang Đạo, &hellip; đường cao tốc tr&ecirc;n kh&ocirc;ng, v&agrave;nh đai 3, v&agrave;nh đai 2, v&agrave;nh đai 2.5, &hellip; Vinhomes Phạm H&ugrave;ng gần rất nhiều dự &aacute;n lớn xung quanh như l&agrave;: Keangnam, Sudico, Five Star Mỹ Đ&igrave;nh, Golden Palace, Golden Palace A, Mbland Trung K&iacute;nh, Chelsea Park, Mandarin Garden, Vinhomes Mễ Tr&igrave;, Vinhomes Trần Duy Hưng, Indochina Plaza, FLC Mỹ Đ&igrave;nh, Dophin Plaza &hellip; Gần nhiều tiện &iacute;ch xung quanh như: C&ocirc;ng vi&ecirc;n cầu giấy, BigC, rạp chiếu phim, cung tri thức H&agrave; Nội, Trung t&acirc;m hội nghị Quốc Gia, S&acirc;n vận động Quốc Gia, khu đ&ocirc; thị Trung H&ograve;a Nh&acirc;n Ch&iacute;nh, bến xe Mỹ Đ&igrave;nh &hellip;</p>
                    <p>Với ưu điểm vượt trội của hạ tầng ti&ecirc;n tiến c&ugrave;ng hệ thống đường bộ v&agrave; đường tr&ecirc;n cao hiện đại tại trung t&acirc;m Mỹ Đ&igrave;nh, Vinhomes Skylake kh&ocirc;ng chỉ l&agrave; chốn an cư,lạc nghiệp được c&aacute;c chủ nh&acirc;n ưu t&uacute; v&agrave; chuy&ecirc;n gia nước ngo&agrave;i &ldquo; chọn mặt gửi v&agrave;ng&rdquo;, m&agrave; c&ograve;n sở hữu những tiềm năng đầu tư kh&ocirc;ng&nbsp; thể chối từ.</p>
                    <p><strong>KIẾN TR&Uacute;C TINH TẾ, TẦM NH&Igrave;N TUYỆT MỸ</strong></p>
                    <p>Kh&ocirc;ng chỉ l&agrave; tuyệt t&aacute;c kiến tr&uacute;c hiện đại, Vinhomes Skylake l&agrave; sự bứt ph&aacute; về kh&ocirc;ng gian, được ấp &ocirc;m bởi thi&ecirc;n nhi&ecirc;n kho&aacute;ng đạt thấm đẫm sắc xanh mộc &ndash; thủy h&ograve;a quyện.</p>
                    <p>Được thiết kế theo phong c&aacute;ch nghỉ dưỡng hiện đại, do AEDAS &ndash; c&ocirc;ng ty tư vấn kiến tr&uacute;c h&agrave;ng đầu thế giới đảm nhận, c&aacute;c căn hộ hướng thủy tại Vinhomes Skylake sỡ hữu ban c&ocirc;ng rộng r&atilde;i l&ecirc;n tới gần 7m2, xứng đ&aacute;ng l&agrave; kh&ocirc;ng gian thư gi&atilde;n l&yacute; tưởng của bạn mỗi ng&agrave;y.</p>
                    <p>Thiết lập &ldquo;c&ocirc;ng vi&ecirc;n bầu trời&rdquo; ngự trị tr&ecirc;n tầng cao, bể bơi tr&agrave;n bờ với thiết kế độc đ&aacute;o c&ugrave;ng những mặt k&iacute;nh d&agrave;i tới 3m ấn tượng, Vinhomes Skylake mang thiết kế chuẩn mực của những &ldquo;dinh thự&rdquo; ven hồ l&yacute; tưởng.</p>
                    <p>Mỗi sản phẩm bất động sản Vinhomes mang theo hơi thở của cuộc sống mới, năng động v&agrave; hiện đại, đồng thời kiến tạo phong c&aacute;ch sống mới cho người d&acirc;n với quy hoạch đồng bộ, nh&agrave; ở chất lượng, dịch vụ xứng tầm, c&ugrave;ng hệ thống tiện &iacute;ch &ldquo;tất cả trong một&rdquo; (All-in-one), m&ocirc;i trường trong l&agrave;nh v&agrave; an ninh đảm bảo. Tất cả tạo n&ecirc;n một hệ gi&aacute; trị sống vượt bậc theo &ldquo;ti&ecirc;u chuẩn Vinhome&rdquo;.</p>
                    <p><img class="aligncenter size-full wp-image-316" src="http://sanvinhomes.net/wp-content/uploads/2016/12/sk1-1.jpg" sizes="(max-width: 1280px) 100vw, 1280px" srcset="http://sanvinhomes.net/wp-content/uploads/2016/12/sk1-1.jpg 1280w, http://sanvinhomes.net/wp-content/uploads/2016/12/sk1-1-300x214.jpg 300w, http://sanvinhomes.net/wp-content/uploads/2016/12/sk1-1-768x548.jpg 768w, http://sanvinhomes.net/wp-content/uploads/2016/12/sk1-1-1024x731.jpg 1024w" alt="sk1" width="1280" height="914" /></p>
                    <ul>
                    <li>&nbsp;Mỗi căn hộ đều sở hữu thiết kế vượt trội với mặt bằng tho&aacute;ng rộng v&agrave; được bố tr&iacute; linh hoạt, gi&uacute;p tối đa c&ocirc;ng năng sử dụng</li>
                    <li>T&ograve;a S1 , S2 được thiết kế&nbsp;bể bơi ngo&agrave;i trời l&agrave;m th&aacute;c tr&agrave;n c&oacute; k&iacute;nh gi&uacute;p qu&yacute; kh&aacute;ch c&oacute; thể nh&igrave;n ra hồ điều h&ograve;a 19ha</li>
                    <li>T&ograve;a S3 được thiết kế bể bơi 4 m&ugrave;a nằm trong t&ograve;a nh&agrave;.</li>
                    <li>T&ograve;a S1 được thiết kế 36 tầng v&agrave; x&acirc;y dựng cảnh quan vườn dưỡng sinh tr&ecirc;n n&oacute;c để lấy view cho S2 v&agrave; S3.</li>
                    <li>100% ph&ograve;ng ngủ đều c&oacute; mặt tho&aacute;ng đ&oacute;n &aacute;nh s&aacute;ng v&agrave; hầu hết c&aacute;c căn đều c&oacute; khe tho&aacute;ng ở khu vực bếp gi&uacute;p cuộc sống nơi đầy c&agrave;ng trở n&ecirc;n gần gũi với thi&ecirc;n nhi&ecirc;n hơn bao giờ hết</li>
                    <li>Nội thất tất cả căn hộ sẽ sử dụng nội thất Koller của Đức</li>
                    <li>Tất cả c&aacute;c mặt ngo&agrave;i sẽ được bao bọc phần lớn bằng k&iacute;nh low-e để tận dụng tối đa view hồ<br /><img class="aligncenter size-full wp-image-374" src="http://sanvinhomes.net/wp-content/uploads/2016/11/16711561_171246140038083_3382356589880528273_n.jpg" sizes="(max-width: 960px) 100vw, 960px" srcset="http://sanvinhomes.net/wp-content/uploads/2016/11/16711561_171246140038083_3382356589880528273_n.jpg 960w, http://sanvinhomes.net/wp-content/uploads/2016/11/16711561_171246140038083_3382356589880528273_n-300x208.jpg 300w, http://sanvinhomes.net/wp-content/uploads/2016/11/16711561_171246140038083_3382356589880528273_n-768x534.jpg 768w" alt="16711561_171246140038083_3382356589880528273_n" width="960" height="667" /></li>
                    </ul>
                    <p>&nbsp;</p>
                    <p><strong>MẶT BẰNG T&Ograve;A S3</strong></p>
                    <p><strong>T&ograve;a S3</strong></p>
                    <p>Số tầng: 42 tầng.<br />Mật độ:20 căn/s&agrave;n.<br />Số thang m&aacute;y:&nbsp;13<br />Diện t&iacute;ch (T4 &ndash; T24): 50,99m2-170m2.<br />&ndash; 2&nbsp;căn 1PN/s&agrave;n: 50,99m2.&nbsp;<strong>Gi&aacute; chỉ &nbsp;từ 1,9 tỷ &nbsp;( Full Vat + Nội thất )&nbsp;</strong><strong>&nbsp;</strong><br />&ndash; 8 căn 2PN/s&agrave;n: 62m2 &ndash; 74,4m2.&nbsp;<strong>Gi&aacute; chỉ từ 2,6 tỷ&nbsp;( Full Vat + Nội thất )&nbsp;</strong><br />&ndash; 8 căn 3PN/s&agrave;n: 90m2 &ndash; 118m2.&nbsp;<strong>Gi&aacute; chỉ từ 4,1 tỷ&nbsp;( Full Vat + Nội thất )</strong><br />&ndash; 2 căn 4PN/s&agrave;n:170m2 &nbsp;<strong>Gi&aacute; chỉ từ 9 tỷ&nbsp;( Full Vat + Nội thất )</strong></p>
                    <p>Tầng 23: Sử dụng l&agrave;m ph&ograve;ng kỹ thuật.</p>
                    <p><strong>DỊCH VỤ 5 SAO CỘNG ĐỒNG ĐẲNG CẤP</strong></p>
                    <p>Ph&aacute;t triển cuộc sống v&agrave; sự nghiệp của bạn ngay tại kh&ocirc;ng gian sống của tổ ấm, c&ugrave;ng với những người h&agrave;ng x&oacute;m đồng điệu , ưu t&uacute; , hay đơn giản l&agrave; nh&acirc;m nhi một t&aacute;ch caf&eacute; s&aacute;ng cuối tuần sau những giờ tập s&ocirc;i động tại ph&ograve;ng gym.</p>
                    <p>Dịch vụ quản l&yacute; theo ti&ecirc;u chuẩn 5 sao của Vinhomes sẽ l&agrave; &ldquo;trợ thủ đắc lực&rdquo;, gi&uacute;p bạn tận hưởng trọn vẹn quỹ thời gian qu&yacute; gi&aacute; của m&igrave;nh cho gia đ&igrave;nh v&agrave; sự nghiệp.</p>
                    <p>Năm trong khu vực được nhiều người nước ngo&agrave;i lựa chọn bởi ti&ecirc;u chuẩn quốc tế cao, c&ugrave;ng khung gian sống như mơ với mật độ c&acirc;y xanh v&agrave; diện t&iacute;ch mặt nước l&yacute; tưởng, Vinhomes Skylake sẽ l&agrave; &ldquo;mảng đ&aacute;t v&agrave;ng&rdquo; quy tụ cộng đồng cư d&acirc;n đẳng cấp.</p>
                    <p>Kh&ocirc;ng chỉ thoải m&atilde;n những y&ecirc;u cầu khắt khe về tiện &iacute;ch sống, Vinhomes Skylake c&ograve;n l&agrave; nơi cuộc sống th&ecirc;m thăng hoa khi những t&acirc;m hồn đồng điệu t&igrave;m thấy nhau, khi gi&aacute; trị văn h&oacute;a v&agrave; nh&acirc;n văn được tr&acirc;n trọng</p>
                    <p><img class="aligncenter size-full wp-image-217" src="http://sanvinhomes.net/wp-content/uploads/2016/11/99707.jpg" sizes="(max-width: 960px) 100vw, 960px" srcset="http://sanvinhomes.net/wp-content/uploads/2016/11/99707.jpg 960w, http://sanvinhomes.net/wp-content/uploads/2016/11/99707-300x167.jpg 300w, http://sanvinhomes.net/wp-content/uploads/2016/11/99707-768x426.jpg 768w" alt="99707" width="960" height="533" /></p>',
                    'active' => 1,
                    'hot' => 1,
                    'category_id' =>2
            ],
            [
                'title' => 'TỔNG QUAN DỰ ÁN VINHOMES WEST POINT',
                'slug' => 'tong-quan-du-an-vinhomes-west-point',
                'image' => '2018_11_06_76ff5a0c8cf3956836c701ce8c32dc42.jpg',
                'teaser' => 'The Information Technology industry has witnessed exponential growth over the years, and if you want to be a part of this growing industr...',
                'content' => '<div dir="ltr">
                    <p><strong>Vinhomes West Point</strong>&nbsp;l&agrave; dự &aacute;n Khu đ&ocirc; thị hạng sang. Với nhiều loại h&igrave;nh ph&aacute;t triển như: Vincom, T&ograve;a nh&agrave; văn ph&ograve;ng cho thu&ecirc;, Căn hộ Vinhomes&hellip; V&agrave; hệ thống quần thể tiện &iacute;ch của Vingroup, dự &aacute;n được Quản l&yacute; v&agrave; vận h&agrave;nh bởi đơn vị Vinhomes. Dự kiến trong thời gian tới,&nbsp;<strong>Vinhomes West Point</strong>&nbsp;sẽ l&agrave; dự &aacute;n căn hộ &ldquo;Hot&rdquo; nhất ở khu vực Ph&iacute;a T&acirc;y của Thủ đ&ocirc;.</p>
                    <p>Tọa lạc tr&ecirc;n mảnh đất v&agrave;ng tr&ecirc;n đường Đỗ Đức Dục, b&ecirc;n cạnh l&agrave; trung t&acirc;m hội nghị Quốc Gia. Dự &aacute;n<strong>Vinhomes West Point</strong>&nbsp;Đỗ Đức Dục c&ograve;n c&oacute; rất nhiều ưu điểm kh&aacute;c như thiết kế ấn tượng, với 100% c&aacute;c ph&ograve;ng b&ecirc;n trong căn hộ rộng r&atilde;i v&agrave; tho&aacute;ng m&aacute;t. Ngo&agrave;i ra quần thể&nbsp;<strong>Vinhomes West Point</strong>&nbsp;Đỗ Đức Dục được quy hoạch với nhiều kh&ocirc;ng gian c&acirc;y xanh, c&ugrave;ng những tiện &iacute;ch tiện nghi.</p>
                    <h3>VỊ TR&Iacute;&nbsp;VINHOMES WEST POINT&nbsp;ĐỖ ĐỨC DỤC NẰM Ở Đ&Acirc;U???</h3>
                    <p><strong>Chung cư Vinhomes West Point</strong>&nbsp;sở hữu tới 2 mặt tiền đường lớn l&agrave; đường Phạm H&ugrave;ng v&agrave; đường Đỗ Đức Dục. Đ&acirc;y được xem l&agrave; khu vực trung t&acirc;m với hệ thống hạ tầng được đồng bộ h&oacute;a v&agrave; đầu tư hiện đại.</p>
                    <p>Trong v&ograve;ng b&aacute;n k&iacute;nh chưa tới 300m l&agrave; cư d&acirc;n c&oacute; thể đi tới: Kh&aacute;ch sạn Marriot, Bảo t&agrave;ng H&agrave; Nội, Big C Thăng Long, T&ograve;a nh&agrave; Grand Plaza v&agrave; T&ograve;a th&aacute;p Keang Nam Phạm H&ugrave;ng&hellip;</p>
                    <p><a href="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/vi%CC%A3-tri%CC%81.jpg"><img class="aligncenter size-full wp-image-418" src="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/vi%CC%A3-tri%CC%81.jpg" sizes="(max-width: 960px) 100vw, 960px" srcset="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/vị-trí.jpg 960w, http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/vị-trí-300x164.jpg 300w, http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/vị-trí-768x421.jpg 768w" alt="" width="960" height="526" /></a></p>
                    <div id="attachment_516" class="wp-caption aligncenter">&nbsp;</div>
                    <p>Với lợi thế vị tr&iacute; gần những khu c&ocirc;ng vi&ecirc;n điều h&ograve;a tại khu vực T&acirc;y H&agrave; nội gồm c&oacute;: Hồ điều h&ograve;a tại Khu đ&ocirc; thị Skylake Phạm h&ugrave;ng, Hồ điều h&ograve;a Ph&ugrave;ng Khoang, Hồ điều h&ograve;a Mễ Tr&igrave;, Khu C&ocirc;ng vi&ecirc;n Cầu Giấy,&hellip;</p>
                    <ul>
                    <li>C&aacute;ch bảo t&agrave;ng H&agrave; nội 200m</li>
                    <li>C&aacute;ch t&ograve;a nh&agrave; Keang Nam 600m</li>
                    <li>C&aacute;ch Dự &aacute;n D&rsquo; capital trần Duy hưng: 800m</li>
                    <li>C&aacute;ch SVĐ quốc gia Mỹ Đ&igrave;nh: 1.5 km</li>
                    <li>Trong v&ograve;ng b&aacute;n k&iacute;nh 2km l&agrave; rất nhiều trường học v&agrave; bệnh viện v&agrave; những khu chung cư cao cấp</li>
                    </ul>
                    <p>Đ&acirc;y cũng l&agrave; dự &aacute;n c&oacute; vị tr&iacute; l&yacute; tưởng ngay khi nằm trong khu vực c&oacute; tốc độ ph&aacute;t triển bậc nhất Việt Nam.</p>
                    <h3>TỔNG QUAN MẶT BẰNG DỰ &Aacute;N</h3>
                    <p><a href="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/viber-image7.jpg"><img class="aligncenter size-full wp-image-333" src="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/viber-image7.jpg" sizes="(max-width: 1280px) 100vw, 1280px" srcset="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/viber-image7.jpg 1280w, http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/viber-image7-300x212.jpg 300w, http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/viber-image7-768x543.jpg 768w, http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/viber-image7-1024x724.jpg 1024w" alt="" width="1280" height="905" /></a></p>
                    <p>Khu căn hộ Vinhomes West Point&nbsp;chia l&agrave;m 3 t&ograve;a: N1, N2, N3 đầy đủ c&aacute;c tiện &iacute;ch từ tầng căn hộ, 04 tầng TTTM:<br />* T&ograve;a N2 cao 39 tầng; N3 cao 35 tầng: T&ograve;a căn hộ chung cư cao cấp sang trọng:<br />+ Căn hộ 1 ph&ograve;ng ngủ: 54m2;<br />+ Căn hộ 2 ph&ograve;ng ngủ: 65m2 &ndash; 77m2;<br />+ Căn hộ 3 ph&ograve;ng ngủ: 93m2 &ndash; 109m2;<br />+ Căn hộ 4 ph&ograve;ng ngủ: 127m2 &ndash; 129m2.<br />* To&agrave; N1 cao 39 tầng : Khối văn ph&ograve;ng kết hợp lưu tr&uacute; (Office Tell):<br />+ Căn hộ 1 ph&ograve;ng ngủ: 65m2;<br />+ Căn hộ 2 ph&ograve;ng ngủ: 73m2 &ndash; 129m2;</p>
                    <p><strong>MẶT BẰNG TỔNG THỂ</strong></p>
                    <p><a href="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/5-1.jpg"><img class="aligncenter size-full wp-image-414" src="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/5-1.jpg" sizes="(max-width: 961px) 100vw, 961px" srcset="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/5-1.jpg 961w, http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/5-1-300x169.jpg 300w, http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/5-1-768x432.jpg 768w" alt="" width="961" height="540" /></a></p>
                    <p><a href="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/M%E1%BA%B7t-b%E1%BA%B1ng.jpg"><img class="aligncenter size-full wp-image-415" src="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/M%E1%BA%B7t-b%E1%BA%B1ng.jpg" sizes="(max-width: 960px) 100vw, 960px" srcset="http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/Mặt-bằng.jpg 960w, http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/Mặt-bằng-300x162.jpg 300w, http://sangiaodichvinhomes.vn/wp-content/uploads/2017/03/Mặt-bằng-768x414.jpg 768w" alt="" width="960" height="517" /></a></p>
                    <p>&nbsp;</p>
                    <h3>TIỆN &Iacute;CH VINHOMES WEST POINT ĐỖ ĐỨC DỤC C&Oacute; G&Igrave;???</h3>
                    <p>C&ugrave;ng với điểm mạnh l&agrave; hệ thống cơ sở hạ tầng tiện &iacute;ch đồng v&agrave; hiện đại nhất nh&igrave; H&agrave; nội, đ&atilde; khiến cho dự &aacute;n khu đ&ocirc; thị Vinhomes trở th&agrave;nh 1 dự &aacute;n tiềm năng tốt hơn bao giờ hết tại thị trường bất động sản năm 2018. V&agrave; cũng mang tới cuộc sống tiện nghi vượt trội cho cộng đồng d&acirc;n cư nơi đ&acirc;y.</p>
                    <div id="attachment_520" class="wp-caption alignnone">
                    <p><img class="size-full wp-image-520" src="http://vinhomes-doducduc.com/wp-content/uploads/2017/03/tien-ich-chung-cu-vinhomes-melodia.jpg" sizes="(max-width: 704px) 100vw, 704px" srcset="http://vinhomes-doducduc.com/wp-content/uploads/2017/03/tien-ich-chung-cu-vinhomes-melodia.jpg 704w, http://vinhomes-doducduc.com/wp-content/uploads/2017/03/tien-ich-chung-cu-vinhomes-melodia-300x151.jpg 300w" alt="Hệ thống tiện &iacute;ch tại Vinhomes Melodia Đỗ Đức Dục" width="704" height="355" /></p>
                    <p>Hệ thống tiện &iacute;ch tại&nbsp;<strong>Vinhomes West Point</strong>&nbsp;Đỗ Đức Dục</p>
                    </div>
                    <p>Khu Nh&agrave; văn h&oacute;a sinh hoạt chung: L&agrave; địa điểm để tổ chức những hoạt động cộng đồng cho cư d&acirc;n Melodia v&agrave;o những sự kiện lớn nhỏ trong năm.</p>
                    <p>Khu r&egrave;n luyện sức khỏe: Với những hạ tầng chơi thể thao hấp dẫn như bể bơi trong nh&agrave;, ph&ograve;ng Gym chất lượng cao, s&acirc;n b&oacute;ng rổ, s&acirc;n tennis,&hellip; Cho cư d&acirc;n cuộc sống khỏe v&agrave; thư th&aacute;i.</p>
                    <p>Khu TTTM Vincom: Được biết tới như l&agrave; khu trung t&acirc;m mua sắm sầm uất bậc nhất ở Việt Nam hiện nay, với những thương hiệu thời trang lớn, rạp chiếu phim, hệ thống cửa h&agrave;ng đa dạng,&hellip;</p>
                    <p>Khu trường quốc tế Vinschool: Với đầy đủ c&aacute;c cấp học, v&agrave; được trang bị những thiết bị hiện đại, c&ugrave;ng cơ sở vật chất tốt nhất, con em của cộng đồng d&acirc;n cư Vinhomes sẽ được gi&aacute;o dục theo gi&aacute;o tr&igrave;nh ti&ecirc;u chuẩn quốc tế.</p>
                    <p>V&agrave; c&ograve;n rất nhiều những tiện &iacute;ch dịch vụ 5 sao kh&aacute;c,&hellip;.</p>
                    <h3><strong>GI&Aacute; B&Aacute;N VINHOMES WEST POINT&nbsp;ĐỖ ĐỨC DỤC L&Agrave; BAO NHI&Ecirc;U???</strong></h3>
                    <p>Cho tới hiện tại Gi&aacute; b&aacute;n của dự &aacute;n vẫn chưa được Vingroup c&ocirc;ng bố, mặc d&ugrave; v&acirc;y qu&yacute; vị c&oacute; thể tham khảo th&ecirc;m mức gi&aacute; b&aacute;n của 3 si&ecirc;u Dự &aacute;n bao gồm:</p>
                    <ul>
                    <li>Gi&aacute; b&aacute;n Dự &aacute;n<strong>&nbsp;Vinhomes Green Bay&nbsp;</strong>Mễ tr&igrave;:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<strong>35&nbsp;Triệu/m2 &ndash; 55 Triệu/m2</strong></li>
                    <li>Gi&aacute; b&aacute;n Dự &aacute;n<strong>&nbsp;D&rsquo;. Capitale&nbsp;</strong>Trần Duy Hưng:&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<strong>&nbsp; &nbsp;42 triệu/m2 &ndash; 66 triệu/m2</strong></li>
                    <li>Gi&aacute; b&aacute;n Dự &aacute;n<strong>&nbsp;Vinhomes Sky Lake&nbsp;</strong>Phạm H&ugrave;ng:<strong>&nbsp; &nbsp;40 Triệu/m2 &ndash; 65 Triệu/m2.</strong></li>
                    </ul>
                    <h2><strong>NHỮNG L&Yacute; DO N&Ecirc;N CHỌN VINHOMES ĐỖ ĐỨC DỤC</strong></h2>
                    <h3><strong><em>VỊ TR&Iacute; V&Agrave;NG TẠI PH&Iacute;A T&Acirc;Y H&Agrave; NỘI</em></strong></h3>
                    <p><strong>Vinhomes West Point</strong>&nbsp;l&agrave; dự &aacute;n hiếm c&oacute; hiện nay sở hữu vị tr&iacute; đẹp bậc nhất tại khu vực ph&iacute;a T&acirc;y H&agrave; Nội với hai mặt tiền l&agrave; đường lớn Phạm H&ugrave;ng v&agrave; Đỗ Đức Dục. Th&ocirc;ng qua những con đường huyết mạch, kết nối giao th&ocirc;ng chưa bao giờ dễ d&agrave;ng hơn thế đồng thời được thừa hưởng h&agrave;ng loạt những tiện &iacute;ch ngoại khu, mang đến sự thuận tiện nhất cho cuộc sống sinh hoạt của cư d&acirc;n.</p>
                    <h3><em><strong>AN NINH BIỆT LẬP TẠI VINHOMES WEST POINT&nbsp;ĐỖ ĐỨC DỤC</strong></em></h3>
                    <p>Với hệ thống camera hoạt động 24/24 c&ugrave;ng hệ thống an ninh nghi&ecirc;m ngặt, đội tuần tra bảo vệ được đ&agrave;o tạo b&agrave;i bản, đảm bảo an to&agrave;n tuyệt đối cho c&aacute;c cư d&acirc;n đang sinh sống tại dự &aacute;n&nbsp;<strong>Vinhomes West Point</strong>.</p>
                    <h3><em><strong>CỘNG ĐỒNG CƯ D&Acirc;N ĐẲNG CẤP</strong></em></h3>
                    </div>',
                'active' => 1,
                'hot' => 1,
                'category_id' =>2
            ],
        ]);
    }
}
